[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
evm_version = "shanghai"
gas_limit = "18446744073709551615"
libs = ['lib']
memory_limit = 43554432
optimizer = true
optimizer_runs = 100000
via_ir = true
out = 'out'
solc = "0.8.26"
src = 'src'
fs_permissions = [
    { access = "read", path = "./script/setup/" },
    { access = "read", path = "./out/" },
]

[profile.default.optimizer_details]
constantOptimizer = false
yul = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "multi"
tab_width = 4
wrap_comments = false
